### ISSUE TITLE
How to become a committer?

### ISSUE THREAD

**Issue by aodag** [zopefoundation/developer_docs#1]
I wanna commit to zope projects.

[Document](https://github.com/zopefoundation/developer_docs/blob/master/source/becoming-a-committer.rst) tells how to become a committer, but [Zope Commiter Agreement](http://foundation.zope.org/agreements) link is dead.
What I have to do?

**Comment by tseaver** [comment]
I just checked, and the `foundation.zope.org` appserver is running.  However, the files which set up Apache to proxy to it are missing.

**Comment by icemac** [comment]
@tseaver Who could fix this configuration issue?

**Comment by mgedmin** [comment]
I've a copy of the agreement PDF, in case someone wants to sign, scan and email it before we fix the mess:
[ZopeFoundation_Committer_Agreement.pdf](https://github.com/zopefoundation/developer_docs/files/1314164/ZopeFoundation_Committer_Agreement.pdf)

**Comment by hannosch** [comment]
I've added the pdf file directly into this repo, nuked the SVN checkout on the docs.zope.org server and replaced it with a new checkout and build from this GitHub repo.

The docs at http://docs.zope.org/developer/becoming-a-committer.html should be correct again.

**Comment by mgedmin** [comment]
FWIW the Wayback Machine has a snapshot to the old page, but only _some_ of the PDFs themselves: https://web.archive.org/web/20170630110220/http://foundation.zope.org/agreements

**Comment by aodag** [comment]
i'm sure agreement pdf can download from `Becoming a Committer`.
thanks
