### ISSUE TITLE
Move this documentation to RTD?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/developer_docs#2]
Maybe even include into or at least link from https://zope.readthedocs.io/?

(I always have a hard time finding the contributor agreement if someone asks where to find it.)

**Comment by dataflake** [comment]
This documentation is now merged into the repository for www.zope.org (see https://github.com/zopefoundation/www.zope.org). Any further development will happen there and this repository will be set to archived state.

You will find prominent links to the contributor guide right on the front page of www.zope.org now.
